### ISSUE TITLE
`/pat` command incorrectly counting and "allowing" pat

### ISSUE THREAD

**Issue by TeaFive** [FroggyPanda/space-bear-bot#1]
- `/pat` command seems to be "usable" at some point before the 24 hour cooldown was over. More specifically, it displays the embed with the pat GIF, personal pat count, and server pat count.

On my end, the bug did not add to my personal pat count. My next pat should have been at roughly 9:30pm PST, but I was able to "pat" at 9:12am PST today. There is a discrepancy between the leaderboard count (11) and the displayed server count (14). I'm not sure if it's related to this bug though.

May need to observe the command over some days to get more specific details if it would help.

**Comment by FroggyPanda** [comment]
This could have been a side effect of the way I was caching the data.  When the bot crashes I'm not 100% sure it would actually push all the data into the database before it exits.

I will keep this open to see if this problem comes up again.
